version: '3.7'

services:
       app:
        build: .
        volumes:
         - .:/app
         - /node_modules:/app/node_modules
        working_dir: /app
        ports:
         - 3000:3000
        command: ['yarn','serve']

